package mod.jd.botapi;

import jdk.nashorn.internal.ir.annotations.Ignore;
import net.minecraftforge.client.ClientCommandHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;

/**
 *  This is the main class.
 *  This is the main mod class. o_o
 *
 *  The {@link Mod} annotation specifies the Mod's unique ID, it's version and the versions of Minecraft it runs on.
 *  It also specifies that this class is the main Mod Class.
 *  Currently it runs on all versions equal to and above v1.11.2
 *  @see Mod
 * */
@Mod(modid = BotAPI.MODID, version = BotAPI.VERSION, clientSideOnly = true, acceptedMinecraftVersions = "[1.11.2,)", canBeDeactivated = true)
public class BotAPI
{

    public PlayerMovementController pmc;

    // The static data about the mod.
    public static final String MODID = "botapi";
    public static final String VERSION = "1.0";

    // The globally used object of the mod.
    public static BotAPI INSTANCE = new BotAPI();

    @Mod.Metadata
    public static ModMetadata md;

    /**
     * Returns the global and static Mod Instance to be used.
     * Should always be used to get an object of the mod, instead of creating a new object.
     * @see Mod.InstanceFactory
     * @return shopGen.INSTANCE
     */
    @Mod.InstanceFactory
    public static BotAPI getInstance()
    {
        return INSTANCE;
    }

    /**
     * It is the init function which initialises the mod and sets the Mod's Metadata.
     * This function is called by Forge during the Mod Initialisation Phase.
     * @see EventHandler
     * @see ModMetadata
     * @param event
     */
    @EventHandler
    public void init(FMLInitializationEvent event)
    {
        md.autogenerated = false;
        md.version = VERSION;
        md.modId = MODID;
        md.authorList.add("Jaideep Singh Heer");
        md.description = "A Mod create and control bots for automation.";
        md.credits = "Made by the Jaideep Singh Heer.";
        md.name = "BotAPI Mod";

        System.out.println("Initialising BotAPI");
        registerCommands();
        pmc = new PlayerMovementController();
    }

    private void registerCommands() {
        ClientCommandHandler.instance.registerCommand(new mod.jd.botapi.Commands.botCommand());
        ClientCommandHandler.instance.registerCommand(new mod.jd.botapi.Commands.testCommand());
    }

}
